version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: "jdbc:mysql://db:3306/yourdatabase"
      DB_USERNAME: "e3ms"
      DB_PASSWORD: "password"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "e3ms"
      MYSQL_USER: "e3ms"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  db-data: